name: 'Create Terraform Workspace'
description: 'Invoke Terraform API to create workspce in Terraform Cloud.'
inputs:
  workSpaceName:
    description: 'Terraform workspace name'
    required: true
  organizationName:
    description: 'Terraform organization Name'
    required: true
  terraformToken:
    description: 'Terraform Token'
    required: true
  terraformHost:
    description: 'Terraform Host Name'
    required: true
  awsAccessKeyId:
    description: 'AWS Access Key ID'
    required: true
  awsSecretAccessKey:
    description: 'AWS Secret Access Key'
    required: true
outputs:
  workSpaceId: 
    description: 'Terraform WorkspaceId'
runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: 'play'  
  color: 'green'